nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173'] # ton frontend
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: ['Authorization']
        max_age: 3600
    paths:
        '^/': # applique à toutes les routes de l'API
            allow_origin: ['http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_credentials: true
